### ISSUE TITLE
What do the colored face glyphs mean?

### ISSUE THREAD

**Issue by nebelch** [arkayenro/arkinventory#1058]
Just updated to 3.08.03, and some BOP items now have a colored glyph in the lower left corner that looks sort of like a face.  What do these mean?  I can't find anything about them in the settings or the wiki (and I'm reasonably certain that it's ArkInventory drawing them).  My hunch is that it has to do with transmog appearances, but there are at least four different colors and I don't know how to interpret them all.

<img width="120" alt="screen shot 2018-07-22 at 1 21 07 pm" src="https://user-images.githubusercontent.com/41551979/43049769-24cccb6e-8db2-11e8-9395-cd0c6417f9a1.png">

**Comment by arkayenro** [comment]
https://github.com/arkayenro/arkinventory/wiki/Transmog_Status_Icons

i've updated the FAQ as well

**Comment by hollo6** [comment]
Could we please have an option to disable this globally so we don't have to turn it off one by one in every style? That is a huge amount of work for me, using different styles for bag/bank and for every character.

**Comment by nebelch** [comment]
Agreed; this seems like something I'd care about across all my toons (because I'm a transmog fiend) or not at all (because I'm not).

**Comment by nebelch** [comment]
As an acknowledged transmog nut, I like the extra feedback, but not so much the existing glyphs: the face doesn't add any meaning, and the glyphs are not clearly related.  There are two axes: known/known but from a different item, and learnable on this toon/not learnable on this toon.  It would help if on-this-toon axis was a variation in shape or shade, so instead of having to remember that green/yellow means "I don't know this appearance", it's dark-green/light-green or green-circle/green-square.

Honestly, I don't know that the "known appearance, but from a different item" is useful — the only information I really need is: is this safe to sell off, or does it have an appearance I haven't yet learned? — which means you only need two glyphs instead of four.  No glyph = safe to sell.  Maybe that could be another option if a lot of people do care.

**Comment by arkayenro** [comment]
the icons were just something neutral-ish i grabbed out of the wow client, didnt really like them being colour coded as people have colour issues, so changing them to shapes is probably where they'll end up

**Comment by joevt** [comment]
"Known appearance but from a different item" means that you can't select the item as the "Transmogrify as:" option in the Blizzard Appearances UI. This is important to completionists who want to learn not just the appearance but also all the source items as well.

As for the face icons, they all appear to be the same face. Therefore only the color matters. So why not just use a circle instead of a face? Anyway, I prefer the icons used by the Can I Mog It? addon. They have different colors AND shapes. The ALL THE THINGS addon has adopted the same icons. Can I Mog It? actually has a ArkInventory plugin but it's not working 100% in WoW 8.0 (Opening the Bank usually gets them to show up). Can I Mog It? icons also appear in the Blizzard and Skillet Professions UI.

It seems that ArkInventory uses the bottom left corner for the transmog icon. But that is the same corner used by the Upgrade icon. ArkInventory has an option to change it, but it doesn't say what "Default" means. I think the "Default" anchor should be indicated (Bottom Left or whatever it may be).

**Comment by arkayenro** [comment]
i've moved the config options to global and made all the icons white, so now you can pick which icon you want for each state, and what colour you want it to be.  hopefully should cover all expectations

**Comment by Calesta** [comment]
Some recent change in ArkInventory -- perhaps the transmog status icons being discussed here -- is preventing the 'Can I Mog It?' addon from adding it's indicator.  Disabling transmogrify status icons in ArkInventory has no effect.

From my observation, any item that I've had in my inventory for a while has it's 'Can I Mog It?' indicator while newly acquired items don't.  I'm fairly certain that is relevant in some way.

There's a coded workaround in the 'Can I Mog It?' issues if it helps as a reference point.

https://wow.curseforge.com/projects/can-i-mog-it/issues/175 

Hoping that you'll be able to figure out the issue so that users can use either option.

Thanks!

**Comment by arkayenro** [comment]
as per the curse ticket

the reason its no longer working is probably because i no longer to pre-build 50 of the item frames for each bag to get around loading while in-combat issues, they get created as required now.  if youre in-combat then a temporary frame is created, and replaced once you leave combat.

i've added some code that might help, but as i said there, i dont use mogit so not really sure

**Comment by Calesta** [comment]
Thanks for reply and posts in the other thread!  Hopefully the author or one of the maintainers will see it and update accordingly!
