### ISSUE TITLE
Basically all trade goods are classified as WOW_ITEM_CLASS_TRADEGOODS_OTHER

### ISSUE THREAD

**Issue by taylorthurlow** [arkayenro/arkinventory#1201]
I'm wondering if this is an issue on Blizzard's side, but I find myself having to manually tag basically all trade goods into their respective trade goods sections (marking herbs as herb trade goods, etc) in order to get them to sort properly.

**Comment by Archov** [comment]
@taylorthurlow 
I was able to get around this with a fairly simple process of doing some ETL on data from a couple wiki pages to create a rule that calls out items by names. There are some edge cases on some items because the name rule doesn't require exact match, but I believe I got those covered with my "not raw" addition because it was mostly raw fish were matching as cooked fish.

You can find my rules here https://pastebin.com/QefpukUh

I haven't done every profession yet just the mats I've interacted with, if you want some more you can message me on battle.net Archov#1630 and I'll see if I can whip them up for you real quick. Each category usually only takes me 3-5 minutes to convert into a rule.

**Comment by arkayenro** [comment]
you may want to upgrade to the latest alpha, it uses periodictable to categorise most of the classic stuff (retail seems to be categorised much better by itself)

**Comment by arkayenro** [comment]
btw, you may want to use the periodic table rule function pt( "category1", "category2" ) in the rules that way you dont have to list each item out, they've already done most of the work for you

if you go into edit mode, click on the item, then debug > pt item sets it will tell you what sets the item is in, you can copy that and paste it into a rule

**Comment by arkayenro** [comment]
all the categories should be localised in 3.09.00
