### ISSUE TITLE
differentiate crafting materials per profession

### ISSUE THREAD

**Issue by ilreberli** [arkayenro/arkinventory#1244]
For a lot of crafting materials used by engineers like "Energy Cell" or "Spare Parts" I could not find a general rule to assign them to "Crafting Materials for Ingeneers" and I dont want to assign each item by name. Can anybody help me ?

**Comment by arkayenro** [comment]
tt( "tinkering" )

i didnt auto assign them into the engineering category because anyone can use those items via the tinkering robot, you dont need engineering

for other items there are options in the config that let you assign crafting materials to your first/second skill categories, or leave them as crafting mats
