### ISSUE TITLE
separates xmog() behavior and "Secondary sources" option

### ISSUE THREAD

**Issue by Melchiah90** [arkayenro/arkinventory#1304]
Hi,

After inspection it turns out that xmog() behavior relies on the "Secondary sources" option in the configs to decide if an item appearance is considered learnt or not when already unlocked but not from said item. Problem is this option also controls displaying the icons for secondary sources in the bag. So if you use xmog() and don't care about secondaries as long as the appearance is already learnt you have to turn off the option and thus the icons.

I think having this option only deal with displaying the icons and have xmog(bool) to decide whether to take secondary sources into account would be cool. Also I feel like xmog() checking if item is _not_ learnt rather than the opposite is a bit counter intuitive. Thanks.

**Comment by arkayenro** [comment]
xmog is "backwards" because its more for capturing item appearances that you have not learnt yet so you can separate them out and not accidentally sell them.  i really cant see why youd want it to pick up items you had already learnt (thats nearly always all of them)

i originally checked the secondary when using the rule but i thought that if you dont care about displaying it then you probably dont care about it in your rule either so didnt leave it in.

i've updated the function to take a parameter, ie xmog(arg1), where if you set arg1 to true then it will also check secondaries even if your not showing them.  will be in the next release

**Comment by arkayenro** [comment]
transmog( true ) should work in the current alpha 5

**Comment by arkayenro** [comment]
added to 3.09.23
