### ISSUE TITLE
ArkInventory.Frame_Border_Paint tweak parent frame

### ISSUE THREAD

**Issue by AcidWeb** [arkayenro/arkinventory#1391]
Hello,

I would like to politely request to add BackdropTemplate also to parent of frames that are handled by `ArkInventory.Frame_Border_Paint` function.

It might be not useful for you but it makes external skinning easier.

**Comment by arkayenro** [comment]
> It might be not useful for you but it makes external skinning easier.

actually i think it just makes for lazy/bad code in the skinning addon.  their code should be robust enough to check if frames exist, and that they have backdrops, that need to be skinned instead of blindly presuming they do and generating an error because of that.

every frame that needs a background, has a background.  i think the only ones that dont are the hidden bag frames that only exist to parent the slot frames to, and as they arent meant to be visible they should not be skinned in the first place.

even in my own code i have to check if the frame exists, and that it has a backdrop to paint, before i run the actual paint code or it will barf out errors and break my mod - why isnt the skinning addon doing those basic checks?

`if frame and frame:obj:GetBackdrop( ) then`

you would be better off taking the issue up with the skinning addon author so that you end up with more robust code that wont break at the drop of a hat - worse case it will stop skinning a mod when that mod changes, which is to be expected, but thats way better than spitting out errors every time and breaking the rest of the skinning its doing.

**Comment by AcidWeb** [comment]
You misunderstand the issue. Obviously there are check where they should be. But there are some places that require backdrop due too how skin looks that don't have backdrop anymore. And I consider adding additional mixins on skin side as too big interference in addon code that might have unexpected results.

Anyway we will fix is on skin level somehow.
