### ISSUE TITLE
ArkInventory resets Reverse Bag Sort Cvar

### ISSUE THREAD

**Issue by Dalarrus** [arkayenro/arkinventory#1392]
I tried setting the default wow CVAR for reverse sorting, but on reload it will reset, not sure if a bug or if there's just a setting I can't find that's doing this

Version 30941 on Retail/9.0

**Comment by arkayenro** [comment]
do you mean loot to leftmost bag? or something else?

which cvar are you setting?

**Comment by Dalarrus** [comment]
So, I was using Advanced Interface Options' checkbox for it, which I assumed just changed the 'reverseCleanupBags' CVar, but it seems to use the '/run SetSortBagsRightToLeft(true)' command instead of a cvar, which if I have ArkInventory running, will be changed back to false on any UI reload. (And it will even uncheck the box in advanced interface options, interestingly enough)

**Comment by arkayenro** [comment]
right click on the restack icon, make sure the type is set to blizzard, go down to options and untick reverse cleanup bags

and yes, whats set in there will reset the game to match every load.  i cant remember if thats because theres no way to get the current value, or its not available at load. possibly because the cleanup appears to be done server side

**Comment by Dalarrus** [comment]
So yeah, it was just a setting I couldn't find, thanks! :)
