### ISSUE TITLE
Rules for item sets occasionally reset

### ISSUE THREAD

**Issue by viliger2** [arkayenro/arkinventory#1454]
I am not sure what causes this and maybe it's even ItemRack's fault but occasionally items don't follow the "outfit" rule. If I remove every item from the set and put it back then it works again. I have a feeling that it has something to do with level ups, since I just reached 65 and reset happened again, when I re-set'd everything this morning.

**Comment by arkayenro** [comment]
level ups change the item string so its reasonable there might be an issue at that point.

i'll have a look around and see if i can fix it from my side.

**Comment by arkayenro** [comment]
because itemrack saves the itemstring that contains the character level in it then the item no longer matches after a level up.  youd have to update the itemrack set for ai to match again

i think i found a workaround though by converting the itemrack saved itemstring into a "sanitised" itemstring before comparing them.  it seems to work ok and it will be in the next release.

**Comment by arkayenro** [comment]
fixed in 30951
