### ISSUE TITLE
Problem with multiple profiles on TBC Classic

### ISSUE THREAD

**Issue by chadley91** [arkayenro/arkinventory#1484]
I'm experiencing an issue with switching between profiles, where the bars don't seem to save. The issue happens whether I'm switching between characters, or on a single character switching the profile manually.

In the first image I have the active profile set to "Falyn" and bar 2 is set to contain herbs.
![First image](https://i.imgur.com/uBzg6cS.png)

In the second image, I change the active profile to "Racey" and reset bar 2, configuring it to contain enchanting materials.
![Second image](https://i.imgur.com/7uSc4gJ.png)

In the last image I switch back to the profile "Falyn" (where bar 2 should be set to contain herbs), but bar 2 is still set to contain enchanting materials.
![Third image](https://i.imgur.com/7LK1jSg.png)

Any help fixing this would be greatly appreciated! Thanks :)

**Comment by arkayenro** [comment]
the top level profiles are just containers
those style, layout, and category set values are the real profile for each window.

if you want completely different profiles you also need to have create new style, layout, and category sets, and then apply them to the 

it was setup this way so that if all you wanted to do was change the layout between your bank/bag, or other characters, you could while keeping the style and category set the same

**Comment by arkayenro** [comment]
see https://github.com/arkayenro/arkinventory/wiki/UserGuide_Profiles for a more in-depth explanation

**Comment by chadley91** [comment]
ahh got it, I figured it was something that was going over my head! thank you very much, great addon btw :)

**Comment by arkayenro** [comment]
its different to the way other addons use profiles and a lot of people have raised tickets about it so i'm adding that wiki page into the actual config so its explained in there how it works and that should hopefully help reduce the confusion
