### ISSUE TITLE
Lots of Errors on PTR

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1486]
What can I do to help? Seems like there's a ton of issues with the PTR for Classic at the moment.

**Comment by arkayenro** [comment]
classic era or bcc classic?

**Comment by arkayenro** [comment]
its just cosmetic, the explosives, reagents, and devices categories have now been removed in classic and i dont have defaults for those as i removed them when classic originally removed them.

i've added them back in and it should be fixed in the next alpha/release

**Comment by stratoru** [comment]
![image](https://user-images.githubusercontent.com/43893231/128929023-25597f82-ff69-4490-a5a2-46f43ce547d4.png)
![image](https://user-images.githubusercontent.com/43893231/128929041-7bbd91f0-541e-45c0-bad5-d34ececa9025.png)
![image](https://user-images.githubusercontent.com/43893231/128929063-99ef304b-c50c-46de-b3de-b68e74d06a0b.png)
![image](https://user-images.githubusercontent.com/43893231/128929083-9273efe0-a6eb-45ba-90ca-49a00d3f228f.png)
Still getting multiple errors on PTR this week, even since updating to latest alpha release. Arkinventory has been consuming massive CPU resources on the PTR so I don't think this is just cosmetic in nature. Unless there are other addons conflicting with arkinventory causing the huge amount of usage, although no other addons are throwing errors besides this one.

**Comment by arkayenro** [comment]
@stratoru  the missing entries were fixed in an alpha version a week before you posted?  the other error is from itemrack.

please ensure you have the latest version

**Comment by arkayenro** [comment]
fixed in 3.09.55
