### ISSUE TITLE
[BUG] BCC version loading 

### ISSUE THREAD

**Issue by GilfromOverwolf** [arkayenro/arkinventory#1545]
Hello, 
I'm from the CurseForge team - we received a ticket that there is an issue with the Retail/BCC version .toc files.

Ok, if you look at the BCC version - the ArkInventory.toc file contains this first line: ## Interface: 90105
and so it is treated the same as the Retail version through the CurseForge client.

If you have further question - please contact support.curseforge.com

**Comment by arkayenro** [comment]
i tag each variant in curseforge so the toc version should be irrelevant - if its not then why are there client versions on the curse hosting site in the first place?

the toc is mostly irrelevant anyway as there are so many mods out there that havent been updated that the vast majority of people have to enable out of date mods enabled to get those to run - plus they need to turn that off every time the game is updated to a new version (which everyone does)

3.09.61 has client specific toc files/values for all variants - although the tbc variant of the search sub-mod does have the wrong value, which will be fixed in the next alpha/release - but that shouldnt impact the curseforge client and if it does then you need better code.

**Comment by GilfromOverwolf** [comment]
Thanks for the reply!
Sharing the feedback with the devs so we can improve on our end as well, will comment again  if there is any follow up questions.
