### ISSUE TITLE
Detele the custom bars

### ISSUE THREAD

**Issue by statelittle** [arkayenro/arkinventory#1581]
What version number you are using?
3.09.67

What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta
Burning Crusade

What language is the game client set to?
English

Describe
I want to delete the bar 22 - bar 30
but it doesn't work

Screenshots
![World Of Warcraft Screenshot 2022 06 27 - 00 33 17 49](https://user-images.githubusercontent.com/108231732/175826012-f59338af-3681-4c47-8e7e-23a90ef9437b.png)

**Comment by arkayenro** [comment]
bar 22 is already empty according to your screenshot (no assigned categories), but for what looks like a completely empty row (21-26) to exist one of those bars must have a category assigned to it.  just find it and delete that bar and it should collapse down.

in edit mode there will always be one empty row at the top.  its designed that way so that you have easy access to new bars
