### ISSUE TITLE
[BUG] UI Dissapears

### ISSUE THREAD

**Issue by eggnacho** [arkayenro/arkinventory#1631]
**What version number you are using?**
3.10.0.01

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail Live

**What language is the game client set to?**
English

**Describe the bug**
While crafting, i believe its when my bag gets full, my entire UI disappears
**To Reproduce**
Steps to reproduce the behaviour, if possible:
It could possibly be something with the auto sorting 

**Screenshots**
https://i.imgur.com/1lzgjtm.jpg
https://i.imgur.com/WAw5X6S.jpg
**Additional context**
When the ui disappears everything is also pretty laggy and my cursor is of the item i was crafting

**Comment by eggnacho** [comment]
was mass vendoring items and the ui disappeared again. So i dont think its the fact that my bags are full

**Comment by Jarhead101st** [comment]
I had issues with my entire UI disappearing also. I disabled all addons except ArkInventory and have had it occur multiple times since then.

I can replicate it fairly consistently moving items from bags to guild bank and back. This is true for multiple alts and different guild vaults. I've also had it occur in combat while soloing old raids. It may be that was due to full bags.

I wonder if it is due to the new reagent bag slot?

**Comment by eggnacho** [comment]
ive had it occur from bulk vendoring items, bulk looting items, bulk crafting items as well

**Comment by paradisewoods** [comment]
I'm also having this bug, 11/18/2022. I am running the latest release.

**Comment by arkayenro** [comment]
please try 3.10.07 alpha 6
