### ISSUE TITLE
Conflict with Peddler addon (WoTLK) [BUG] 

### ISSUE THREAD

**Issue by RENgOLD** [arkayenro/arkinventory#1646]
Addon not works when Peddler is also loaded.
Error: 
`ArkInventory: Ошибка> Interface\AddOns\Peddler\Peddler.lua:107: Usage: GetContainerItemLink(index, slot)`
Screenshot:
![image](https://user-images.githubusercontent.com/1100128/198853935-de478561-87cd-4c19-a50d-126dfb9a36b8.png)

**Comment by arkayenro** [comment]
without the full error stack that looks like a peddler issue

does peddler have any issues when arkinventory isnt loaded?

**Comment by RENgOLD** [comment]
> without the full error stack that looks like a peddler issue
> 
> does peddler have any issues when arkinventory isnt loaded?
I just rolled back the version of arkInventory to 3.09.68 and everything works fine, including Peddler.
How i can provide full error stack for you?

**Comment by RENgOLD** [comment]
But the error appeared after updating ArkInventory, not Peddler

**Comment by arkayenro** [comment]
you need to install buggrabber and bugsack, those will let you capture the full error stack.

i've redone the code anyway so check next alpha to see if its fixed or not

**Comment by Cartas** [comment]
Hi old chaps!

I'm the author of Peddler.   Firstly, it's an honour that you've even made mention of Peddler in your amazing addon!  💖 

It seems however that you've recently added some new code that is incorrectly calling some Peddler functions with `nil` values, such as in `ArkInventoryJunk.lua:54`.

I've made changes to Peddler Classic that simply returns when getting `nil` values, but it'd be nice to fix ArkInventory so that I don't need to simply hide these errors.

**Comment by RENgOLD** [comment]
Now it works fine with latest versions (includes ArkInventory alpha), thanks everyone :)
