### ISSUE TITLE
[BUG] Super trivial... AI is tinting patterns based on use level of crafted item

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1684]
![image](https://user-images.githubusercontent.com/55365231/203173767-a20da47c-b8aa-4a4e-8999-fd5fefd9b30d.png)

It's tinting the pattern as un-usable due to the item level of the item. But I do have sufficient leatherworking skill to make the pattern usable.

**Comment by ImUnicke** [comment]
Unfortunately this is probably caused by what is currently a bug within the game itself. The new 10.0 API `TooltipUtil.GetDisplayedItem` (and inclusively the old deprecated method `tooltip:GetItem()` ) to retrieve the Item being displayed in a tooltip is bugged and instead of returning the 'Recipe' Item, it returns the 'Crafted' Item of the Recipe. So it's probably related to that and would need AI to include a workaround in some way :(

**Comment by Gogo1951** [comment]
What? A problem with the WoW API?! No, never! =P

I get it, it's super trivial. Let's close this then. 

Thanks mate!
