### ISSUE TITLE
Enable newly created rules for the category set & make enabled/disabled status more visible

### ISSUE THREAD

**Issue by 0xjc** [arkayenro/arkinventory#1737]
One of the most confusing things about rules (I know it's tripped me up several times) is that when you create a new rule, it starts out as disabled for the category set. Furthermore, this fact is not visible in either of the Rule UIs (`/ai rules` or `/ai config` -> Advanced -> Rules). You have to go to `/ai config` -> Settings -> Category Sets -> Rules which is not obvious at all. I then end up trying to figure out why the rule isn't working.

So I have 2 suggestions:
1. make rules enabled for the current category set (or all category sets? I only use one) by default
2. add an indicator for whether the rule is enabled for the current category set (or all category sets?) in both Rule UIs

**Comment by arkayenro** [comment]
rules need to go on a bar, when you do that in edit mode you can see its status.

you could have the rule turned off for the bag and on for the bank - i cant show that in an overall ui which is why the rules ui is so basic.

same reason theyre disabled by default.  you mostly dont want them on in every categoryset.

the categoryset config does show the status of each rule and category

**Comment by 0xjc** [comment]
hm okay I see, fair enough. The reason I was confused is that I would create a rule, go to Edit Mode and click an item to check if it was properly assigned a rule. This obviously wouldn't work if the rule is disabled. I will just have to remember to assign a rule to a bar first.
