### ISSUE TITLE
[BUG] Outfit rule not working on Wrath PTR or Cata Beta

### ISSUE THREAD

**Issue by Ragedaug** [arkayenro/arkinventory#1876]
Arkinventory-3.10.27-alpha-13

Bug applies to Wrath Classic PTR and Cata Classic Beta

English

Currently, for the built in Equipment Manager (EQ), the "outfit()" rule is working in both Retail and in Wrath Classic, which use different front end built in UIs. Wrath PTR and Cata Beta switched from the Wrath EQ to a Retail style EQ, and the rule is not moving equipment to their assigned sections.

![image](https://github.com/arkayenro/arkinventory/assets/98781423/9e79bcc1-9839-4676-b0c0-f9699f2ed016)
![image](https://github.com/arkayenro/arkinventory/assets/98781423/d463ebc5-0e95-493a-8feb-ec8c0a7d2217)
![image](https://github.com/arkayenro/arkinventory/assets/98781423/070af90a-0bbd-4f92-a1f5-2125fd274b46)

**Comment by arkayenro** [comment]
its working for me on the PTR (wrath classic) realms

i dont have cata beta to test there

remove "blood" from the rule to check if it can pickup any set

**Comment by Ragedaug** [comment]
Feels like I have to be doing something wrong, but can't figure it.  I added Itemrack to Cata Beta, created a Frost and Blood set and ArkInventory immediately sorted those sets to the Blood and Frost configured sections, so the rules seem to be working great with the addon. 

These screenshots are from my Warrior on the Wrath PTR, The only thing in my bags are a couple hearthstones and two sets of gear. All the gear is either assigned to Arms or Prot, and I've tested the outfit rule with either set in bags. Neither sorts.  I also tried an all outfit test, please let me know if I didn't do this correctly - Rule: outfit()

The only addons I have installed in the Wrath PTR are Wowhead Looter &  Arkinventory.

![image](https://github.com/arkayenro/arkinventory/assets/98781423/3ced76ff-b211-42e7-9031-4b692d579ae3)
![image](https://github.com/arkayenro/arkinventory/assets/98781423/61f08be1-f4aa-4016-a0b8-2360542729b8)

In the 2nd pic, I have the two EQ sets in the background of the image on the left side.

**Comment by arkayenro** [comment]
run this in game `/dump C_EquipmentSet.CanUseEquipmentSets( )`

it should return true.  if it doesnt then the equipment manager will not be checked.

**Comment by Ragedaug** [comment]
I checked across Wrath Classic, Wrath Classic PTR, Cata Classic Beta, and Retail.  All return the same value: 
```Dump: value=C_EquipmentSet.CanUseEquipmentSets( )
[1]=true```

**Comment by arkayenro** [comment]
ok, so the only difference in that rule function is a check for void storage, which i think just got enabled in cata?  at least its meant to be enabled in cata.  if its not then the rule function will break because the returns from `EquipmentManager_UnpackLocation( location )` are different when void storage is available.

run this in game - it should return true - `/dump ArkInventory.ClientCheck( ArkInventory.Global.Location[ArkInventory.Const.Location.Void].ClientCheck )`

if you edit arkinventoryrules\arkinventoryrules.lua, around line 1160 ish should be this commented out line

`--ArkInventory.Output( setname, ":", k, " -> [", player, ", ", bank, ", ", bags, ", ", void, "] [", bag, ".", slot, "] [", voidtab, ".", voidslot, "] = ", location )`

remove the two minus signs at the front, save the file, and `/reload` ingame

then open your bags and check that output.  void should be nil (unless you have an outfit item in there) but if its not then they havent enabled the void storage yet so the code wont work

i can bump it from cata to pandaria but i was pretty sure void storage was enabled in cata.

**Comment by Ragedaug** [comment]
/dump ArkInventory.ClientCheck( ArkInventory.Global.Location[ArkInventory.Const.Location.Void].ClientCheck )

```
Dump: value:ArkInventory.ClientCheck( ArkInventory.Global.Location[ArkInventory.Const.Location.Void].ClientCheck )
[1]=true
```

You are correct, Void Storage was introduced in Cata along side the Transmog vendor, so we could now store all the gear sets we would be farming.  That said, Blizzard removed the void storage vendor from the Cata beta a few weeks back. Initially the vendor was standing they non-interactive, but in the last few builds, the vendor just got removed.  Some speculation that it was removed because of the account wide retail style Appearances tab was added, so no longer a reason to keep all of your old gear sets in storage, but so far as I'm aware, Blizzard has been silent on what they are doing with Void Storage.

This is what I see when I log into the Cata beta, so the Void Storage issue makes me curious if this is causing the EQ/rules issue:

![image](https://github.com/arkayenro/arkinventory/assets/98781423/aeb30deb-207e-40d8-ae40-9482eb966671)


Also, I did remove the "--" from line 1166, as you show, saved the .lua file, reloaded the game, but the gear still is not sorting with in game EQ, only when I have Itemrack enabled.

**Comment by arkayenro** [comment]
yeah, it looks like they havent actually implemented void storage yet and its screwing it up.  its failing to load the void storage ui addon as well.

i can push it out to pandaria for the moment, and once/if they do bring it back i can set it back to cata to get it to work.

**Comment by arkayenro** [comment]
try [alpha 15](https://www.curseforge.com/wow/addons/ark-inventory/files/5297566)

**Comment by Ragedaug** [comment]
Perfect. Was working as soon as I logged in. Thank you!
