### ISSUE TITLE
[BUG] 3.10.33-alpha-4 incudes error in Titan Panel

### ISSUE THREAD

**Issue by hollo6** [arkayenro/arkinventory#1902]
**What version number you are using?**
3.10.33-alpha-4

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
enGB

**Describe the bug**
Since updating to this version, getting the following error on login/reload:
[09:33:48] Titan: Error:  'Failed_to_Register' 'ArkInventory_Tracking_Bronze' '' 'Interface/AddOns/Titan/TitanLDB.lua:600: Unsupported LDB type 'hidden''

**To Reproduce**
1. Install ArkInventory.
2. Install Titan Panel.
3. log in / reload interface

**Screenshots**
N/A

**Additional context**
I don't know if this would still happen with both addons' all default settings, but I can send mine once I know which ones are relevant to this issue.

**Comment by arkayenro** [comment]
the LDB API states that if the data type cannot be handled it is to be ignored.  i set my LDB objects to "hidden" if they cant be displayed in that game variant, eg the currency object is hidden in classic.  the bronze object is hidden in retail.

does everything still work even with that error?  if it doesnt then titan panel needs to be fixed so that it doesnt generate a hard error.

**Comment by hollo6** [comment]
It _seems_ to still work, but I have no clue what problems it can cause or what I can't see at a glance.
Posted a comment on their page, hoping for a reply.

**Comment by hollo6** [comment]
They removed the printout and it seems to not cause any issues.
