### ISSUE TITLE
[BUG] [TWW Beta] Enabling Warband Bank Causes Error Message

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1907]
**What version number you are using?**
v31033.Alpha.5

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
TWW Beta

**What language is the game client set to?**
English

**Describe the bug**
I finally enabled the Warband bank functionality on the Beta client to test it out.  It doesn't look like it's yet been integrated into the ArkInventory functions UI so I just disabled it, deposited what I wanted to remove from my bags and enabled it again.  Since then, I see the following error message every now and then but I'm not sure what's triggering it.

**To Reproduce**
Steps to reproduce the behaviour, if possible:

**Screenshots**

![Error - After Warband Bank Enabled](https://github.com/arkayenro/arkinventory/assets/13042214/e458fb1e-3a54-427a-9f83-c55eb8b1b318)

**Additional context**

Again, I realize this is an Alpha build and there's probably a lot still being reviewed. I'm simply raising this issue for awareness to help with troubleshooting. Hopeful that it can be resolved for launch!

**Comment by arkayenro** [comment]
bag ids 13 thru 17 are the warbank slots.

im trying to work how i can integrate the account level bank data with character level bank data for those new slots.  i can get it to store into the character data but thats going to screw up item counts.

**Comment by DT-DIY-Tech** [comment]
How do you save guildbank data, wouldn't it be possible to use the same data structure for warband banks?

**Comment by fraerie** [comment]
even if it can't include the inventory counts - as it stands we can't even view the warband bank tab if arkinventory is enabled

**Comment by arkayenro** [comment]
> even if it can't include the inventory counts - as it stands we can't even view the warband bank tab if arkinventory is enabled

so disable it.  dont expect things to just work in a beta

> How do you save guildbank data, wouldn't it be possible to use the same data structure for warband banks?

vault data is stored as its own player, the warband bank is account wide so its closer to heirlooms, the problem was that a location belonged only to a specific player, or guild, or account, and the code could only access and display it that way.  the warbank is account wide but is accessed via the bank interface, its part of the bank, and the code couldnt handle that.

if i made a new window for it then both the bank window and the warbank window would close when you closed the other one because theyre both linked the bank access.

plus whatever i do still needs to work with the other game clients.

i've rewritten most of it now so it should be viable in alpha 6 once i get that uploaded either today or tomorrow.

**Comment by Calesta** [comment]
The latest alpha seems to have fixed the error message and it appears you've added the War Bank functionality to that of the bank view which makes sense to me.  Thanks for all the fixes and new functionality!

**Comment by arkayenro** [comment]
i havent updated the restack code to ignore/support the account bank yet so it will barf until i get that done
