### ISSUE TITLE
Have Warband Bank tabs have their own window.

### ISSUE THREAD

**Issue by Anaral** [arkayenro/arkinventory#1943]
**Is your feature request related to a problem? Please describe.**
It is hard, if not impossible to tell what is currently in the Warband Bank vs. the standard bank.

**Describe the solution you'd like**
I would like to see there be a tab to press that would open the Warband Bank in its own window. 

**Describe alternatives you've considered**
The only alternative I can see, is disabling Ark everytime I want to know for sure what is only in the Warband Bank. This is cumbersome and not really doable since it wouldn't be organized.

**Comment by arkayenro** [comment]
there are right click options on the bag slots to display/hide each bag - you can use this until i can add some buttons to make it easier

**Comment by arkayenro** [comment]
the isolate option in there will hide every other bag except the one you selected (if you only want one tab at a time)

then use the display all when done

**Comment by Biomedic32** [comment]
The above is what I did in the meantime. Edit mode > Categories Assignable > Bag 10-14 (these are your warbank "bags"). put them into their own bar and it should help you see at least whats in the shareable bank and whats not

**Comment by f4ndor** [comment]
I tried the same, but items assigned to custom categories have higher priority. 
I even created a rule, set it to priority 1, with `bag(10,11,12)` and still the custom assigned items wouldn't move.
Looking forward to some sort of solution, but I'm honestly not sure what it might look like.

**Comment by outlying** [comment]
+1 for Improved Warband Bank Management

Currently (version 3.10.33-alpha-28), the Warband bank is combined with the regular character bank. This wouldn't be an issue if it weren't for the [Warband Bank Distance Inhibitor](https://www.wowhead.com/item=216665/warband-bank-distance-inhibitor).

When using the "Warband Bank Distance Inhibitor" it only allows access to the Warband bank. However, at present, accessing the Warband bank (via Inhibitor) with ArkInventory displays both the Warband bank and the standard character bank, including items from the standard bank, even though the character items are not accessible, visible, but not accessible.

The separate Window/Tab for Warband bank would be appreciated:
- it makes more sense to separate as the access scope of the Warband bank is different than character bank - similar to Guild bank , more characters can access it
- currently standard bank is massive, plenty of slots, with Warband bank slots default setup requires scrolling, making it annoying to use (I know we can customize, but new users might be overwhelmed by the size)

I want to thank for all the hard work on this addon, I know it is not easy and takes time - I personally consider it the best bag addon in WoW, I still can't find anything better

**Comment by arkayenro** [comment]
the distance inhibitor wont be an issue as i can tell when that is used so can force it to warbank only.

once i can sort out how to make the panels (bank/reagent bank/account bank) more easily usable the distance inhibitor issue disappears.

ie when opening the bank i could not show the warbank items, you'd have to normal click on the warbank bags (like in the vault) to swap around those, and like the bank it would only show the items from that tab.  a sort of half bank half vault thing.

the main issue is they are currently sort of stuck in the same window as thats how blizzard has them (its how they tell which one is active).

i can pull them out but then i have to make sure that closing the warbank window doesnt kill your bank connection (closing the bank window as well), and vice versa.

two windows might work if people dont mind that closing one will close the other.

i would need to work out how to tell which window is on top/active for right clicks from the bag.

**Comment by arkayenro** [comment]
ok, if i treat the bank like the vault it will open up and only display the bank bags at first, basically what you get if you isolate panel 1.

if you click on the reagent bank bag it will only show that bag
if you click on an account bank bag it will only show that bag

unsure if i should keep the bank and reagent bank together like it originally was or separate it out like the blizzard bank ui does.

its still re-using the hide/show bag code so i may have to remove some of those from the right click menu

**Comment by DravenSA** [comment]
I say split it out like the original UI, 
With a lot of messing around, those that know how to do rules, Category sets and such like should be able to set different rules for each "Tab" so to speak

**Comment by arkayenro** [comment]
let me know what you think about alpha 29

**Comment by Thaldan** [comment]
I feel sad with this change, I had config to show every tab with his own bar, and I could see everything in on windows and just drag and drop item easily, now so much click to do like the blizzard UI. I seem to be the only one, but except if I have miss something in options, I don't like it :(

**Comment by DravenSA** [comment]
I understand that there are so many options here, and it is not easy to keep everyone happy and with something that is so customizable it makes it nearly impossible. and it is very difficult to share a visual in text, so I will see if maybe I can share a Photoshop screenshot and that might help keep more people happy.

So if by default it was all one bag like Alpha 28, but then allow the setting to override the default to something like Alpha 29 but with the option selection not in a right click but at the top bar something like below (please pay no attention to the bag layout, I have removed all rules from the bars, as I have over 100 rules, 30 customs, and 4 profiles... so this is just shell layout ideas.)

![Screenshot 2024-08-02 200444](https://github.com/user-attachments/assets/bee2ef2b-6fea-42ea-a9dc-14b67a131989)

So the one problem I see here is because the bank, reagent and warbank cannot be separated to individual blueprints, switching between them will leave a lot of gaps if you have Show Empty selected and makes everything even worse if you have Clump checked
Eg like below

![Screenshot 2024-08-02 194834](https://github.com/user-attachments/assets/5190e592-9318-4928-8b80-9f796994d657)

I still think that individual bag views, and separate Panel views and all-in-one views is the right direction via settings.

**Comment by DravenSA** [comment]
I see two happy people on the Curse page, but I also see an unhappy person here,  (can only imagine what the mass majority are thinking, ) but hey change is good, and with some tweaks I think you will be able to make almost if not all happy. Keep  up the great work and we ALL appreciate your time and energy you put into this

**Comment by DravenSA** [comment]
Dang nappit, i forgot to mention that the original UI had the option to "include tradeable reagents" can that be added somewhere too, as it freaked my daughter out as she forgot to turn it off and filled her warbank with so much stuff that she didn't want.

**Comment by Biomedic32** [comment]
Is it possible to group warbank bags together in a single window like the personal bank is? I think the regeant bank being together with the personal bank is fine and the majority of people would find more intuitive. I would essentially just split by whats personal and whats warbank and call it good. Then maybe put in an option for users to include the warbank within the same window if they want (to address comments like Thaldans where moving things between personal and warbank is annoying)

overall though, huge improvement with alpha 29.

**Comment by arkayenro** [comment]
i get both/all sides of this.  personally i dont really like the new layout yet, its functional and mimics the default ui but it feels a bit off (plus i dont have all the new options in there yet).  at some point i will need to fix it but i need to play the game with it for a while to see how it feels to know what to change.

personally i preferred one big bag like i started out with, or having two parts (bank + reagent bank, and then all warbank tabs together), but i understand the limitations of having a single blueprint against all of that.

i do need to get it to a point where i can take it out of alpha though.  i also need to get the other parts fixed (theres still a tonne of stuff left) so for the moment this is probably going to be how it is for a while so i can focus on the other parts i need to fix, unless i get an idea on how to code it to make it work in multiple ways.

if i can make it customisable within the current code i will, whats one more option in that config,

**Comment by Thaldan** [comment]
> Keep up the great work and we ALL appreciate your time and energy you put into this

Of course, I'm nothing but grateful for this addons since BC, and appreciate all this time and effort. 

> i get both/all sides of this. personally i dont really like the new layout yet, its functional and mimics the default ui but it feels a bit off (plus i dont have all the new options in there yet). at some point i will need to fix it but i need to play the game with it for a while to see how it feels to know what to change.
> 
> personally i preferred one big bag like i started out with, or having two parts (bank + reagent bank, and then all warbank tabs together), but i understand the limitations of having a single blueprint against all of that.
> 
> i do need to get it to a point where i can take it out of alpha though. i also need to get the other parts fixed (theres still a tonne of stuff left) so for the moment this is probably going to be how it is for a while so i can focus on the other parts i need to fix, unless i get an idea on how to code it to make it work in multiple ways.
> 
> if i can make it customisable within the current code i will, whats one more option in that config,

I don't know if it's possible, but may be the solution is to have one windows for bank bags + reagent and one windows with warbanks tab on other one who can be both open at the same time via an option/button? And probably more lighter to charge this way?

And for the warbanks tab an option to make it work like the guild bank or like the "normal" bank (all in one view or "tab view" (and implement that on the guild bank too if it's possible, my dream it's to see all the tab in one view with this too, Drag and drop without switching tab will be a banger to "clean this room" after chids... sorry I mean guild mates, make a mess. xD

I'm just an IT guy not a dev one so I don't really know what it's possible or not and how it's complex to make it work. It's just a suggestion than may be make anyone happy (if it's possible xD)

Anyway, once again thx for your time since all this years. Happy or sad about a change, I'm nothing but grateful about addons writers and specially you. This addons is a pilar of my interface since almost his creation ^^.

**Comment by DT-DIY-Tech** [comment]
I tried alpha 29 and there seems to be a major issue. I can't access most bank tabs, they are shown as empty even though I have items. Refresh doesn't help, but in edit mode it shows all items correctly. It's different for every character, which tabs are shown and which aren't. Even those tabs that aren't shown can be interacted with, I can deposit items by right clicking, they just don't appear there.
![image](https://github.com/user-attachments/assets/687663df-9803-4e49-bba0-6bceb2a23848)
Warband Tab 1
![image](https://github.com/user-attachments/assets/e914f70a-86bc-45f7-bb90-a9cdf6d8172f)
Warband Tab 1 in Edit Mode

Now to add my 2 cents to the rest of the discussion. I like the approach in alpha 29, I agree with arkayenro that it feels a bit off, but it is way better than before. Right now the containers at the bottom act like tabs (except for the bank bags). Maybe it would be best to seperate those in the UI, make the bags left aligned and the "tabs" right aligned or the other way around. That way it is a bit clearer why some "bags" switch your view and others don't.

There are a lot of different opinions on what the interface should look like. Maybe the easiest way to satisfy the most people is to implement the following: The buttons that act as tabs right now, could be made to work additively with shift click. What I mean by that is, when I click on the bank tab it shows the bank. If I shift click on the reagents tab, then those items get added to my view. The same goes for the warband tabs.

Or you could just add a bunch of buttons to cover all bases: Bank, Reagent, Bank+Reagent, Warband1...5, Warband all, All.

Or you could make those buttons editable, similar to the bars in the bags, instead of assigned categories per bar it would be assigned views per button. This is probably the most work, but if Blizzard really removes bags from the bank, like they said they would in an interview and replace them with tabs, then it could pay off in the future.

**Comment by outlying** [comment]
> So the one problem I see here is because the bank, reagent and warbank cannot be separated to individual blueprints, switching between them will leave a lot of gaps if you have Show Empty selected and makes everything even worse if you have Clump checked
> Eg like below

@DravenSA but you can have separate layouts per "container", I'm using different layout for my bags and different for bank, as I don't keep some of the stuff in my character bank

**Comment by arkayenro** [comment]
> I tried alpha 29 and there seems to be a major issue. I can't access most bank tabs, they are shown as empty even though I have items.

its a bug in alpha 29 when i changed from display to ignore, fixed in 30 (the display value is reset for everything)

for the bank layouts i'll be adding options to;
* leave it as is (panels for the bank and its bags, the reagent bank, and one for each warbank tab)
* make the bank and reagent bank form a single panel
* make all warbank tabs form a single panel
* combine all bank, reagent bank, and warbank tabs into a single panel (one big bank). i dont think anyone will use this but its easy to add the way its coded.

the downside is that changing the layout currently needs a reload, i cant do it on the fly

the vault will remain as is, the API doesnt allow scanning or data return across multiple tabs, only the current tab, so it cant ever be combined (until blizzard change the API to be like the warbank) - basically the downside to the current API is that when you move an item from one tab to another it would return data only for the target tab, effectively leaving a ghost item in the source tab until you went back to that source tab so it can be rescanned, only then would the ghost item would disappear.

**Comment by DravenSA** [comment]
> > So the one problem I see here is because the bank, reagent and warbank cannot be separated to individual blueprints, switching between them will leave a lot of gaps if you have Show Empty selected and makes everything even worse if you have Clump checked
> > Eg like below
> 
> @DravenSA but you can have separate layouts per "container", I'm using different layout for my bags and different for bank, as I don't keep some of the stuff in my character bank

I do have different layouts for my bag, for my bank and for my bags... my point was different layout for bank bags, reagent bag, and warbank

**Comment by DravenSA** [comment]
> > I tried alpha 29 and there seems to be a major issue. I can't access most bank tabs, they are shown as empty even though I have items.
> 
> its a bug in alpha 29 when i changed from display to ignore, fixed in 30 (the display value is reset for everything)
> 
> for the bank layouts i'll be adding options to;
> 
> * leave it as is (panels for the bank and its bags, the reagent bank, and one for each warbank tab)
> * make the bank and reagent bank form a single panel
> * make all warbank tabs form a single panel
> * combine all bank, reagent bank, and warbank tabs into a single panel (one big bank). i dont think anyone will use this but its easy to add the way its coded.
> 
> the downside is that changing the layout currently needs a reload, i cant do it on the fly
> 
> the vault will remain as is, the API doesnt allow scanning or data return across multiple tabs, only the current tab, so it cant ever be combined (until blizzard change the API to be like the warbank) - basically the downside to the current API is that when you move an item from one tab to another it would return data only for the target tab, effectively leaving a ghost item in the source tab until you went back to that source tab so it can be rescanned, only then would the ghost item would disappear.

Sounds great, but I think the only one you are missing unless it will come through and separate options is Panel 1 all bank bags, Panel 2 Reagent bag, and panel 3 all warbank tabs.
unless I read your post wrong, but either way , it sounds like a great way forward.

Realy loving the greyed out effect per bag, makes it much clearer as to what you can add to each panel so to speak.

**Comment by Thaldan** [comment]
@arkayenro I like what you do, and everyone can be happy like that I think. May be add some buttons to switch between the display choice mode. But it's not a priority.

But with alpha 32 the "bag 7" are missing in the bar bag and not display his contant too (but it appear on the right click menu)

(Don't judge me, I like to see everything at once xD)
![Ark Bank 1](https://github.com/user-attachments/assets/43e2cf7f-1ef9-4d71-8f81-bee4ed9c2cf0)
![Ark Bank 2](https://github.com/user-attachments/assets/604d63e4-a081-457c-bb82-96d23c3437cc)

**Comment by DravenSA** [comment]
ABSOLUTELY LOVE LOVE LOVE ALPHA 32

Perfect in every way, the options cover everything, if someone cant find the right combination for themselves, then they need to try other bag addons, and see what a pleasure this is to work with 
LOVE IT!!!!!!

(sad to say

> But with alpha 32 the "bag 7" are missing in the bar bag and not display his contant too (but it appear on the right click menu)

 an oversight I am sure)

One day if you can keep it on your books, would be awesome to have separate blueprints for each section of the bank, but nowhere near a priory, as I know you are wanting to play that actual game.

Thanks again we ALL appreciate your work.

**Comment by arkayenro** [comment]
sorry, bag 7 was meant to be hidden if you were running a client before wrath and i coded it to hide it after wrath instead

will be fixed in the next alpha

**Comment by Biomedic32** [comment]
i second Dravens comment, absolutely perfect way of handling it in 32. great job as always

**Comment by DravenSA** [comment]
Here is something i discovered today, I have different blue prints for banking character and a different one of everyday characters, and they work fantastic, but the combining of bags, eg bank, reagent warbank etc is global, and not specific to blue prints. Will that be something that changes in the future? 
Everyday toons, have bank and reagent separate, but my bank toon works better if they are combined.
Heavey toons like herbers or miners, again work better separated, but leveling toon work better when combined.

And yip, I have several blueprints depending on the toon, the level, eg leveling v's Max, (timerunners for now), and even one to help clean up the bags at the end of every expansion. and the bags v's bank v's vault all have different blueprints with different layouts and styles.

(if you are not fully using the functions, are you even using Ark Inventory? LOL)

**Comment by arkayenro** [comment]
i think this is all sorted out and working ok now for everyone?

theres no plans to allow blueprints to work against specific panels (not saying never, but its just too hard at the moment to make that work).

**Comment by Anaral** [comment]
I am very happy with the changes made. Thank you for your hard work. I'd truly be lost in WoW without ArkInventory.
