### ISSUE TITLE
Bags are suddenly unsorted

### ISSUE THREAD

**Issue by GoogleCodeExporter** [arkayenro/arkinventory#271]
```
Downloaded from > googlecode | wowinterface | curse | wowui | other (specify)
This morning when I logged in all my bags were unsorted. They were working
fine last night, and I haven't done anything with ArkInventory since they
were last working.

What steps will reproduce the problem?
1. Logging in and opening bags
2.
3.

What is the expected output? What do you see instead?

I expect to see the bags sorted the way I set them up. I see them
completely unsorted, no bars set up, no values assigned to items.
What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `kath.m...@gmail.com` on 30 Aug 2009 at 2:35

**Comment by spiralofhope** [comment]
I, too, had some random issue explode and murder my precious ArkInventory lua.  I believe I had the game client crash.

I've since been extremely aggressive on backups.  After every serious set of changes to AI, I log out and back things up.

I perform backups before addon updates and after any major configuration changes I make.

Perhaps data corruption is a problem with blizzard, or perhaps AI can more aggressively save data.  I don't know.

**Comment by arkayenro** [comment]
closing old issues - if its still a problem re-open the ticket

plus that file doesnt belong to AI, more likely auctionator

**Comment by spiralofhope** [comment]
As an aside, I've had the game client explode a few times since this ticket was opened.  Blizzard has changed things such that my luas seem quite safe now.

Still, backups are good!  All my addon configs are in a git repository now.  =)
