### ISSUE TITLE
Void Storage

### ISSUE THREAD

**Issue by FelixFTW** [arkayenro/arkinventory#746]
I am unable to view Void Storage using the Ark Inventory interface.  Instead, it opens the classic Blizzard UI.  Is this working as intended?

**Comment by joevt** [comment]
I believe this is as intended. Use the Toggle Location menu in the Bags window to view the Void Storage in ArkInventory.

Void Storage is for view only, like Mail and Pets. It has no Override option in the Controls settings like Bags and Bank so it won't replace the normal Void Storage UI.

Just because a window doesn't have the Override option doesn't mean it can't do things with the items. For example, the Pets window lets you summon a pet by clicking on a pet. Right click lets you rename or release a pet.

Some extra coding could be added to allow the Void Storage window to do stuff. For example, I've made changes to Mail window to let me retrieve an item that I click on.

**Comment by arkayenro** [comment]
working as intended, void storage is view only
