### ISSUE TITLE
All my rules are gone!!

### ISSUE THREAD

**Issue by subs-comps-git** [arkayenro/arkinventory#748]
After a disconnect from the game, all my rules are now gone! I had about 30 rules but now when I open the rules windows they've disappeared. This is the second time something like this has happened? Is there a way to recover my rules? Where are the rules actually stored?

Thanks in advance for any help.

**Comment by Gobscheidt** [comment]
I have had this exact same problem it seems that the .lua file with all my custom rules and such has just randomly been deleted. The folder that it is supposed to be contained in (C:\Program Files (x86)\World of Warcraft\WTF\Account\SavedVariables) in is currently empty.

I'm guessing that by the resounding silence that this issue has faced since it was first raised over 2 months ago suggests that file is gone for good and nobody knows why so suck it up and spend hours re-configuring the rules and make sure to back up the file in future.

**Comment by arkayenro** [comment]
see https://github.com/arkayenro/arkinventory/wiki/SavedVariableFile

take backups - of your entire WTF folder so youve got a backup of every mods settings
