### ISSUE TITLE
Splitting/Limiting Stacks

### ISSUE THREAD

**Issue by stonedune** [arkayenro/arkinventory#752]
Having difficulty seeing if something is possible.
I would like to setup a rule that pulls and keeps a set number of items in a frame then applies any other rules to the rest of the stack. Trying to keep long-term crafting project stuff organized.

Example- I'm farming for the Mechano-Hog and I would like to have it pull 40 Copper Bolts and put them in a new frame and have whatever is left over and keep them grouped with my engineering stuff. I would like to expand to include all reagents for a particular recipe as well. 

If someone could help me that'd be great.

**Comment by joevt** [comment]
There's the Count function. https://github.com/arkayenro/arkinventory/wiki/RuleFunction_Count
But it returns true for when stack size is >= count which is not what you want. Also, any number of stacks could return true, when maybe you only want one.

This issue would require some modifications to arkinventory and the Rule handling code. The Rule handling code would need the following:

1) Allow lua function instead of just a lua expression.
2) Allow variables to be created.
3) Allow one optional function for initialization which is executed at the start of the categorization code. Here you would set HasOneMechanoHogBoltsStack = false.
4) Allow one optional function for releasing any allocated memory (if you allocated a table at init time or maybe tables should be reusable to make it faster)
5) Allow one function which can use variables and returns a true or false result. Here, if HasOneMechanoHogBoltsStack is false then you would check the stack size of bolts and set it to true if you found the stack, and return true. Otherwise return false.

The categorization code would have to iterate on bag/slot items if it doesn't already (maybe it iterates on item type now?).

This will work if you have the stack of 40. Additional code would be required to make a stack.

Maybe all of the above could be encompassed by a new rule function called RequiredStack(count) which would return true for the first count items encountered. Any items that return true for RequiredStack will not return true for another rule containing RequiredStack function. Maybe RequiredStack could also force a restack if the current stacks overflow the count. Hopefully a restack won't occur all the time since the categorization code should iterate over the items and rules in the same order each time (arkinventory will have to do some work to make that true when it has to do a restack, so that the stacks for the RequiredStack function remain earlier than the stack that is overflowed). A restack will occur every time you get a new bolt, if count is not a multiple of the stack size.

Then there should be a RequiredForRecipe(recipeName, count) function where count is the number of items you want to create. Maybe this should recursively go through the recipes - for example, if it requires bolts and you don't have all the bolts, then it should find the recipe that makes bolts and include ore that is used to make the bolts. The Skillet Trade Skills addon does this. This won't be possible if you don't know the recipes required. That case can be partially covered by RequiredStack function.

The arkinventory restack button would need to be changed so it doesn't stack together bag/slot items that are in different categories (if that isn't true already).

**Comment by stonedune** [comment]
Awesome, thank you for the information. Would like to add this to the potential features. I really like arkinventory unfortunately don't have much to contribute myself other than strange ideas.

**Comment by arkayenro** [comment]
ai isnt coded to handle that type of very specific categorisation.  ai is more of a generic layout tool.  what youre asking for is incredibly specific, and while im sure it could be coded for (its basically a shopping list) ai cannot do that, nor do i think it would ever be able to
