### ISSUE TITLE
Game Freeze when Caging/Learning Pets or Learning Toys

### ISSUE THREAD

**Issue by Dwelp** [arkayenro/arkinventory#755]
The game always freezes whenever I cage/learn pets or toys.

To be more specific:
- If I learn a pet with the Pet window open, it will freeze a couple of seconds after I close the Pet window
- if I learn a pet with the Pet window closed, it will freeze a couple of seconds after learning the pet
- If I cage the pet (having the pet window open), it will freeze a couple of seconds after closing the pet window

It is similar with toys.

This will not occur if I disable ArkInventory. This occurs if ArkInventory is the only enabled addon. 
I can't figure out why this is happening.

**Comment by joevt** [comment]
Try doing some profiling. Here's an example:
http://www.wowace.com/addons/npcscan-overlay/tickets/50-performance-issue-with-minimap-overlay/

This will tell you what functions in ArkInventory are causing the problem.

It's probably some kind of pet scanning routine (there are a lot of pets to scan).

**Comment by arkayenro** [comment]
pets are a giant random list, as such it has to be scanned completely all the time something happens.  if you have a lot of pets it can can a couple of seconds and its intensive enough to just freeze up the game

the scan only runs if the pet window is closed, which is why if you need to do multiple pet actions its best to leave it open until youre done and it will scan when you close it.

same goes for toys and  mounts (mounts are a bit better in legion)

**Comment by Dwelp** [comment]
Is there any way to disable the automatic scan and do it manually instead?
Alternatively, lower the intensity of it (so it takes more time in the background, but doesn't affect performance).

**Comment by arkayenro** [comment]
not in the current version, i didnt allow people to disable the pet scanning for some reason.

you will be able to disable the pets, mounts and toybox in the legion version though (there was another request for it before)
