### ISSUE TITLE
Doesn't work with 7.0.4

### ISSUE THREAD

**Issue by makedir** [arkayenro/arkinventory#768]
Tested the new builds (3.06.09 and the before), none work, just doesn't load the addon.

**Comment by Yanngo** [comment]
Did you check the checkbox "Load outdated addons" before logging a char?

**Comment by makedir** [comment]
Oh, no, I don't, do I need to do that? ....... of course... what kind of
question is that? I am playing Wow since 10 years... it's not working.

**Comment by Yanngo** [comment]
It is a valid question because I made such mistakes in the past and yes, I've been playing WOW since TBC. To err is human.
If I were a GM, I'd tell you to disable all the other addons, delete the cache folder and then fire up ArkInventory.
You can also install BugGrabber.
http://mods.curse.com/addons/wow/bug-grabber

**Comment by makedir** [comment]
Cool, thx for the tips. You're kidding right? YES I DID THAT TOO, WHAT DO
YOU THINK? I deselected ALL other addons, just Arkinv, and logged into an
alt char => NOT WORKING.

**Comment by makedir** [comment]
http://i.imgur.com/LMsHwBg.jpg

**Comment by Yanngo** [comment]
Special characters in your character's name may be a problem. Try enabling the addon for all chars on the realm?

**Comment by arkayenro** [comment]
german server?

**Comment by arkayenro** [comment]
if so go to locale\dede.lua and comment out the following lines (add two minus signs at the start) so they look like the ones below

line 300
--	L["CONFIG_AUTO_OPEN"] = "\195\182ffne %1$s %2$s beim %3$s" -- program, bag

and line 309
--	L["CONFIG_AUTO_CLOSE"] = "schlie\195\159e %1$s %2$s beim %3$s"

will be fixed in .10 (well cleared until someone translates it again)

**Comment by makedir** [comment]
Yes, German server. No, char name irrelevant, tested others too. Didn't you
say in your first answer there was no problem and all was working?

**Comment by makedir** [comment]
Still not working.

**Comment by arkayenro** [comment]
try 3.06.10 and let me know if its still happening.

**Comment by makedir** [comment]
seems to work now

**Comment by makedir** [comment]
http://i.imgur.com/Vl91q7F.png ...

**Comment by arkayenro** [comment]
should work in 30700 beta 4, let me know if it isnt

**Comment by makedir** [comment]
where to get that beta?

**Comment by makedir** [comment]
got it, will test, thx

**Comment by makedir** [comment]
totally broken o0 http://i.imgur.com/wuqegfF.png arent you testing yourself
before you publish builds? better try to think more instead of trial and
error... thats bad programming.

**Comment by arkayenro** [comment]
of course i test it, im using the thing myself so its not totally broken, its just you

the screenshot is pointless it looks fine.  i presume you have more bags than is actually being displayed?

you havent explained your actual issue yet so perhaps do that and i might be able to work it out

**Comment by makedir** [comment]
Are you nuts? "looks normal" This is how it looks with the previous
version: http://i.imgur.com/ISycuwA.jpg THAT is normal.

**Comment by arkayenro** [comment]
yes very, so stop trying to piss me off.

you did not explain your actual issue anywhere above, and just posted a screenshot of a normal looking bag window and you expect me to work out whats wrong?

if you dont tell me how it used to look or whats missing how am i supposed to know whats wrong with it?  so thankyou for the second screenshot and saying thats how it used to look.

create a new profile and change to it - does it still appear wonky?
assign your current category set to it and test again, then assign the style, test, assign the layout, test
work out which part is broken so i can look at the code that does that part

**Comment by makedir** [comment]
ISSUE: BROKEN WITH NEWEST BETA (see broken screenshot)
NON ISSUE: WORKING WITH 3.06.17 (see working screenshot)

THE END

**Comment by arkayenro** [comment]
fine, goodbye

**Comment by makedir** [comment]
Cant you read? You are asking me seriously "if you dont tell me how it used
to look or whats missing how am"!? LOOK AT THOSE TWO DAMN SCREENSHOTS.

BOTH ARE THE SAME PROFILE, THE SAME CHARACTER. THE ONE IS WITH STABLE
(WORKING), THE ONE BROKEN IS WITH THE BETA.

Publish this broken beta to stable and you will make a lot of the people
using your addon very very happy :-)

**Comment by Yanngo** [comment]
Mr Makedir! Why don't you cool down your temper? You get these addons for free, right? It's not like you are Arkayenro's boss and pay his salary. Even if you donate, you have no right to talk shit like that.

And try to explain your issues better next time. Make it clearer. Explain what you are not satisfied with. Contribute to the discussion. Don't be a big baby just because we don't understand what pains you.

And I wonder why you cannot just use the version that works? I use 3.06.17 and quite satisfied with it. I am not touching the latest betas because I am afraid of bugs, testing and making tickets takes time and, as we can see, some skills. Why don't you do the same?

**Comment by makedir** [comment]
Sorry :> Maybe was a bit vivid on what I said. Glad to see you agree though
the betas are totally useless and full of bugs.

**Comment by makedir** [comment]
Could you please... PLEASE stop destroying arkinventory with every update?
Maybe beta test before releasing or changing...

all custom sorts / rules arent working anymore.
