### ISSUE TITLE
Increase performance, in particular memoize rule functions

### ISSUE THREAD

**Issue by jcai1** [arkayenro/arkinventory#857]
Hello, I love your addon but I've always had performance issues with long freezes when opening bag / bank. I've determined the main issue is that the rule functions don't cache their data. For example if I have 5 rules of the form `equip() and ilvl(a, b)` then `ArkInventoryRules.System.equip` and `ArkInventoryRules.System.itemlevelstat` are called 5 times on each item, whereas it should be possible to just query the equip location and item level once for the item. This is a big problem for tooltip as well since `ArkInventory.TooltipSetHyperlink` is very expensive and it should be possible to just cache the tooltip string. 

You can also cache the result of `loadstring` to avoid compiling rule functions a lot, although the performance gain here is more minor.

Finally, in `ArkInventory.ItemCategoryGet`, you can avoid the call to `ItemCategoryGetDefault` if `ItemCategoryGetPrimary` succeeds, another modest performance gain.

**Comment by arkayenro** [comment]
> I've always had performance issues with long freezes when opening bag / bank
ive only recently been getting them in the bank. i think the larger bags now is getting to where its impacting a lot more.

> the rule functions don't cache their data
the functions themselves, no, they are isolated and dont need to.  the function that calls them to determine an items category does cache the result though, if it didnt it would be horrendous.

>  should be possible to just cache the tooltip string.
you know its 1-25 of left and right strings, not one large string?  each one has to be searched individually

> you can avoid the call to ItemCategoryGetDefault if ItemCategoryGetPrimary succeeds
no, i cant, i need to know both (the returned values should have made that clear).  both the default and primary are cached anyway, so only the first time through is a performance hit.

one thing i have done in the next version is cache the no category return result, this stops it from re-running against non categorised items every refresh.  ie instead of returning nil the primary category function now returns false on no match, this false result gets cached and when checking the cache i specifically check for a nil instead of just "not" before i ask it to check again.

**Comment by jcai1** [comment]
> the functions themselves, no, they are isolated and dont need to.

Regardless of the code structure, the end result is that when I put a call to, say, `ilvl` in 5 different rules, `ArkInventory.ObjectInfo` gets called 5 times as a result, which seems rather wasteful. When AI is testing an item against a barrage of rules, we know it's the same item being tested each time so it's reasonable to cache the item's attributes as they are requested. Then clear the cache when we move on to the next item.

> you know its 1-25 of left and right strings, not one large string? each one has to be searched individually

That's not such a big deal, it can still be cached. Also for a quick fix, we can cache the most recently used tooltip simply by not clearing it; more info below.

> no, i cant, i need to know both (the returned values should have made that clear). both the default and primary are cached anyway, so only the first time through is a performance hit.

You're right, I read the precedence wrong in the return statement.

Anyways what I've found is that the biggest performance increase for me was actually the following hack, in `ArkInventoryTooltip.lua`

```
local lastHyperlinks = {}

function ArkInventory.TooltipSetHyperlink( tooltip, h )

	if h and lastHyperlinks[tooltip] == h then
		return
	end

	if lastHyperlinks[tooltip] == nil then
		lastHyperlinks[tooltip] = ""
		tooltip:HookScript("OnTooltipCleared", function() lastHyperlinks[tooltip] = "" end)
	end
	
	tooltip:ClearLines( )
	
	local osd = ArkInventory.ObjectStringDecode( h )
	
	if h and ( osd[1] == "item" or osd[1] == "spell" ) then
		lastHyperlinks[tooltip] = h
		return tooltip:SetHyperlink( h )
	end
	
end
```

I used the following procedure to profile time spent by AI:

* turn on scriptProfile CVar
* logout and login, wait for load to finish
* /run ResetCPUUsage()
* open bank
* /run local a={}for k,v in pairs(ArkInventory)do if type(v)=="function"then local t=GetFunctionCPUUsage(v,true)if t>0 then tinsert(a,{k,t})end end end sort(a,function(a,b)return a[2]>b[2]end)for i=1,min(#a,25) do print(a[i][1],a[i][2])end

Here are the results:

```
===== Before Tooltip caching hack =====
Frame_Main_Generate 5169.77327162
Frame_Main_DrawLocation 5169.7137423854
Frame_Main_Draw 5169.6620135333
Frame_Main_DrawThreadStart 5169.5934522769
Frame_Container_Draw 5117.5599746775
EVENT_WOW_BANK_ENTER 5074.1931325433
Frame_Main_Show 4993.87957359
TooltipSetHyperlink 3620.9978906124
Frame_Container_Calculate 3487.8946275071
Frame_Container_CalculateBars 3487.7509362512
ItemCategoryGet 3471.9046645466
ItemCategoryGetPrimary 3187.3664184503
ItemCategoryGetRule 3173.8200279336
ObjectInfo 2130.5196943235
Frame_Bar_DrawItems 1206.8427418262
ObjectInfoEquipLoc 525.14925416027
Frame_Item_Update_Lock 505.03288887575
Frame_Item_Update_Texture 286.7075735145
ItemCategoryGetDefault 277.93953307732
ObjectInfoTexture 274.16702178934
Frame_Item_Update_Stock 263.61926251079
ItemCategoryGetDefaultActual 252.83338629382
Frame_Main_Search 188.82960598215
ObjectStringDecode 135.26889560543
TooltipFind 113.81989655872

===== After Tooltip caching hack =====
Frame_Main_Generate 1529.8943499777
Frame_Main_DrawLocation 1529.8405683933
Frame_Main_Draw 1529.812651235
Frame_Main_DrawThreadStart 1529.7703649512
EVENT_WOW_BANK_ENTER 1501.7300427215
Frame_Container_Draw 1481.0130479871
Frame_Main_Show 1424.0760036424
Frame_Container_Calculate 895.7068337098
Frame_Container_CalculateBars 895.55000496761
ItemCategoryGet 884.13476104965
ItemCategoryGetPrimary 720.18591185239
ItemCategoryGetRule 707.38425258788
TooltipSetHyperlink 433.53088828292
Frame_Bar_DrawItems 378.55502430846
ObjectInfo 283.6219064299
ItemCategoryGetDefault 158.34160584421
ItemCategoryGetDefaultActual 141.76866693106
Frame_Item_Update_Stock 138.24658897486
Frame_Item_Update_Lock 136.29238789413
Frame_Main_Search 112.39037383538
ObjectStringDecode 105.00341164096
TooltipFind 97.012535625168
TooltipContains 88.482201579947
ScanLocation 77.555507932168
Scan 77.550581374822
```

For context, I have all bag and bank slots filled with 30-slot bags, and I have 5 rules that call `tooltip`.

**Comment by arkayenro** [comment]
i've recoded the ArkInventoryRules.AppliesToItem and ArkInventory.ItemCategoryGetRule functions to cache the item until it changes, then tweaked the rule functions to use the cached data instead of asking for it..

the tooltip "caching" ive done as well, just slightly differently.  it only needs to check the scan and rule tooltips, not anything else and as those are mine i can add variables to them to identify them, as well as keep a record of the previous hyperlink
