### ISSUE TITLE
ArkInventory.lua:3510

### ISSUE THREAD

**Issue by sappyfeet** [arkayenro/arkinventory#865]
[13:38:44] ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventory.lua:3510: attempt to index local 'i' (a nil value)

This pops a few times when logging in, after a while it stops and the addon loads.  Kind of annoying.

**Comment by Booser** [comment]
I also have this issue. But by me it does not get better after a while. My bag window is totally destroyed and every time i open the bags the message comes one more time.
Here is some screenshot how my bag looks. Its the black thingy in the upper left corner ;)

Oh, because it says something about locale. I am using the german client setting.

![wowscrnshot_092216_223538](https://cloud.githubusercontent.com/assets/704577/18765227/fdc8b3f8-8114-11e6-8f8d-d87932244ba2.jpg)

**Comment by arkayenro** [comment]
> sappyfeet: 3510: attempt to index local 'i' (a nil value)

ive added a workaround for the next version that will get around it but i havent been able to work out why is happening in the first place

> booser: My bag window is totally destroyed and every time i open the bags the message comes one more time.

go into config > workarounds and disable the in-combat yielding, then open the bags.  you should get a full error stack that you can post here

**Comment by Booser** [comment]
When i use the new version the bag works fine again. No distortions. No difference when I toggle in-combat yielding. No error stack.

**Comment by arkayenro** [comment]
will need to add another workaround for mythic keystones, seems blizzard have made the last part of the itemstring completely custom depending on the item

**Comment by arkayenro** [comment]
fixed in 30712
