### ISSUE TITLE
displaying Artifactpower items in wrong bag

### ISSUE THREAD

**Issue by Tatuunka** [arkayenro/arkinventory#950]
Hi, im using 3.07.29 since yesterday and after the update the artifact power tokens are in my main bag.
Although i have one bag marked for them, the addon wont display them in there.
I didnt change anything in my settings, only updated the addon via twitch client.
Any Suggestions what went wrong or how i can fix this ?

**Comment by arkayenro** [comment]
enable edit mode and check what category/rule they are assigned to

then check the bar where they are supposed to go has that assigned to it

**Comment by Tatuunka** [comment]
ok, i assigned them now to usable>artifact power again, but i have to do it for all items seperately . Since when, and why are they not assigned automatically like before ? 

Thx for your fast feedback and your great work on this addon

**Comment by arkayenro** [comment]
in edit mode what category were the ap items assigned to?  ie what is their default category (the one in light yellow, not the one in green)

what language is your game set to?

**Comment by sselicrem** [comment]
I have the same issue - all my AP tokens changed default cat. to Soulbound[0403]. Game language is Russian

**Comment by Cofibib** [comment]
Same here in french client.
To fix it, in local/game.lua I've changed line 218 with this : L["WOW_TOOLTIP_ARTIFACT_POWER"] = FormatForCapture( ARTIFACT_POWER )
(That's its old value from previous version).

The issue seems linked to : * added - artifact power and ancient mana items will now display their values in the ilvl field (if item level is displayed)
And so fixing like I said will disable this change but the artifact power items will go back to the good category.

Exemple of artifact power text in french : "Utiliser : Confère 18 millions de points de puissance à l'arme prodigieuse que vous maniez."
Articaft power can also be displayed with a dot "18.6 millions"

**Comment by arkayenro** [comment]
looks like its a non-english format issue

what do you get if you type (copy/paste) these into your chat window;

`/run ArkInventory.Output( ArkInventory.Localise["ARTIFACT_POWER"] )`

and

`/run ArkInventory.Output( ArkInventory.Localise["WOW_TOOLTIP_ARTIFACT_POWER"] )`

**Comment by Cofibib** [comment]
First one : "Puissance prodigieuse"
Second one : "([%d,.]+)(.-) Puissance prodigieuse"

But like you see from my last comment, "Puissance prodigieuse" don't appear in the numeric part of the tooltip. It's only displayed in light yellow before "Soulbound" line in tooltips.

**Comment by arkayenro** [comment]
yep, i also worked out to change my client language to french, or any of the others, so ill fix the ap assignment and see if theres a way to get the amounts in non-english languages

**Comment by Cofibib** [comment]
If it can help, "Angry World Quests" is able to display the amount in french client.

**Comment by Tatuunka** [comment]
the tip from  Cofibib  helped my fixing the bag issue, no numbers displayed for now, thats fine for me :-)

**Comment by arkayenro** [comment]
3.07.30 should fix the ap tokens

ive got millions translated for most languages but will need to work on the other suffixes, especially thousand and thousands

**Comment by Cofibib** [comment]
Working fine. Thanks.
